{
    'name': "METRC",
    'version': '14.0',
    'author': "Socius IGB",
    'category': 'Generic Modules',
    'website': 'sociusigb.in',
    'summery': '',
    'demo': [],
    'images': [],
    'depends': ['base', 'stock', 'point_of_sale', 'product', 'website', 'mrp'],
    'data': [
        'security/ir.model.access.csv',

        'data/metrc_test_account.xml',
        'data/customer_type_sync_cron.xml',
        'data/facility_sync_cron.xml',
        'data/lot_sync_cron.xml',
        'data/patient_sync_cron.xml',
        'data/pos_order_sync_cron.xml',
        'data/product_sync_cron.xml',
        'data/sale_order_sync_cron.xml',
        'data/strain_sync_cron.xml',
        'data/transfer_type_sync_cron.xml',
        'data/location_type_sync_cron.xml',
        'data/locations_sync_cron.xml',
        'data/uom_sync_cron.xml',
        'data/metrc_user_group.xml',

        'views/pos_config.xml',
        'views/product_template.xml',
        'views/res_partner.xml',
        'views/stock_picking.xml',
        'views/stock_warehouse.xml',
        'views/stock_production_lot.xml',
        'views/stock_location.xml',
        'views/uom_uom.xml',
        'views/website.xml',
        'views/res_users.xml',

        'wizards/message.xml',
        'wizards/package_split.xml',
        'wizards/metrc_sync_item.xml',

        'views/metrc_accounts.xml',
        'views/metrc_facilities.xml',
        'views/metrc_strains.xml',
        'views/metrc_customer_types.xml',
        'views/metrc_transfer_types.xml',
        'views/metrc_location_types.xml',
        'views/metrc_logs.xml',

        'views/actions_menus.xml',

        'reports/shipping_manifest.xml',
    ],
    'installable': True,
    'application': True,
}
